server:
  port: ${TEST_APP_PORT:8080}
  servlet:
    context-path: ${TEST_APP_SERVLET_CONTEXT_PATH:/rest/api/v1}
  error:
    include-stacktrace: always
  compression:
    enabled: ${TEST_APP_SERVLET_COMPRESION_ENABLED:true}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: Test mamartin
  jackson:
    default-property-inclusion: non_absent
  main:
    web-application-type: reactive
---
spring:
  profiles: "dev"
logging:
  level:
    root: warn
    com.altran: debug

---
spring:
  profiles: "des"
logging:
  level:
    root: warn
    com.altran: info

---
spring:
  profiles: "pre"
logging:
  level:
    root: warn
    com.altran: info

---
spring:
  profiles: "pro"
logging:
  level:
    root: error
